@startuml
start
:Letzte nachrichtenposition laden;
:Maximaler Füllstand laden;
if(maximaler Füllstand > letzte nachrichtenposition)
  :Inkrementieren;
  :Nachricht aus dem Speicher laden;
  :Nachricht in den Speicher der Message Queue speichern;
endif
end
@enduml
