@startuml
title Linienfolger mit Kollisionkontrolle

participant "Motorcontroller" as motor << Prio 2 >>
participant "Distanzsensor" as distanz << Prio 3 >>
participant "Farbsensor" as farb << Prio 1 >>

[-> distanz ++ #DarkSalmon: start
 
distanz --> motor --++ #DodgerBlue: vTaskDelay 
motor --> farb --++ #aqua: vTaskDelay
note right
  Farbsensor wird nur ausgeführt
  wenn die anderen Task die CPU abgeben
end note


|||
|||
farb --> distanz --++ #DarkSalmon: preemption
distanz --> farb --++ #aqua: vTaskDelay

|||
|||

farb -> motor --++ #DodgerBlue: rot
note left
  Motor wartet bis eine Nachricht
  von den Sensoren kommt
end note


"motor" --> "distanz" --++ #DarkSalmon: preemption
"distanz" -> motor --++ #DodgerBlue: obstacle
@enduml